# Makefile script to build the DnD World Builder program

.PHONY: all install uninstall build test clean deep-clean

# Performs install and then build in the same command
all:
	echo: "Build everything..."

# Installs the required dependencies
install:
	echo: "Installing dependencies..."

# Uninstalls the required dependencies
uninstall:
	echo: "Uninstalling dependencies..."

# Builds the project files into a exe program
build:
	echo: "Building project... "

test:
	echo: "Test project..."

# Deletes all files from the build folder
clean:
	echo: "Deleting build artifacts... "

# Deletes the entire build folder
deep-clean:
	echo: "Deleting build folder... "
